"""Project-wide constants for the Vera deterministic engine."""

BOT_VERSION = "1.0.0"
TEAM_NAME = "Vera Deterministic Systems"
DEFAULT_PORT = 8080

SEND_AS_VERA = "vera"
SEND_AS_MERCHANT = "merchant_on_behalf"

STRATEGY_LOSS_AVERSION = "LOSS_AVERSION"
STRATEGY_OPPORTUNITY = "OPPORTUNITY"
STRATEGY_CURIOSITY = "CURIOSITY"
STRATEGY_URGENCY = "URGENCY"
STRATEGY_REACTIVATION = "REACTIVATION"

TIME_BUCKET_FALLBACK = "current"

MAX_ACTIONS_PER_TICK = 5

