"""Static mappings used by analyzers and builders."""

TRIGGER_CLASSIFICATION = {
    "perf_dip": ("performance_drop", "problem"),
    "seasonal_perf_dip": ("performance_drop", "problem"),
    "perf_spike": ("performance_spike", "opportunity"),
    "milestone_reached": ("milestone", "opportunity"),
    "research_digest": ("research", "info"),
    "category_research_digest_release": ("research", "info"),
    "regulation_change": ("compliance", "problem"),
    "category_trend_movement": ("trend", "opportunity"),
    "festival_upcoming": ("festival", "opportunity"),
    "ipl_match_today": ("event", "opportunity"),
    "weather_heatwave": ("weather", "problem"),
    "local_news_event": ("local_event", "problem"),
    "competitor_opened": ("competition", "problem"),
    "dormant_with_vera": ("reactivation", "problem"),
    "winback_eligible": ("reactivation", "problem"),
    "renewal_due": ("renewal", "problem"),
    "customer_lapsed_soft": ("recall", "problem"),
    "customer_lapsed_hard": ("recall", "problem"),
    "recall_due": ("recall", "problem"),
    "appointment_tomorrow": ("appointment", "info"),
    "trial_followup": ("followup", "opportunity"),
    "wedding_package_followup": ("followup", "opportunity"),
    "review_theme_emerged": ("review_theme", "problem"),
    "scheduled_recurring": ("curiosity", "info"),
    "curious_ask_due": ("curiosity", "info"),
    "active_planning_intent": ("planning", "opportunity"),
    "supply_alert": ("supply_alert", "problem"),
    "category_seasonal": ("seasonal", "opportunity"),
    "gbp_unverified": ("profile_verification", "problem"),
    "cde_opportunity": ("education", "opportunity"),
    "chronic_refill_due": ("refill", "problem"),
}

CATEGORY_DEFAULTS = {
    "dentists": {
        "tone": "clinical, peer-to-peer, precise",
        "allowed": ["recall", "scaling", "fluoride", "IOPA", "patient cohort"],
        "taboo": ["cure", "guaranteed", "miracle", "best in city"],
        "salutation": "Dr. {name}",
    },
    "restaurants": {
        "tone": "operator-to-operator, busy, practical",
        "allowed": ["covers", "footfall", "orders", "AOV", "match-night"],
        "taboo": ["guaranteed packed house", "viral guarantee"],
        "salutation": "Hi {name}",
    },
    "salons": {
        "tone": "friendly, practical, service-led",
        "allowed": ["walk-ins", "bridal", "haircut", "spa", "trial"],
        "taboo": ["guaranteed glow", "miracle"],
        "salutation": "Hi {name}",
    },
    "gyms": {
        "tone": "coaching, motivational, specific",
        "allowed": ["trial", "membership", "batch", "retention"],
        "taboo": ["guaranteed weight loss", "miracle transformation"],
        "salutation": "Hi {name}",
    },
    "pharmacies": {
        "tone": "trustworthy, precise, health-safe",
        "allowed": ["refill", "stock", "adherence", "OTC"],
        "taboo": ["cure", "guaranteed", "doctor approved"],
        "salutation": "Hi {name}",
    },
    "generic": {
        "tone": "clear, practical, merchant-first",
        "allowed": ["calls", "views", "customers", "offer"],
        "taboo": ["guaranteed", "miracle"],
        "salutation": "Hi {name}",
    },
}

CTA_BY_INTENT = {
    "problem": {
        "performance_drop": "Create offer",
        "review_theme": "Fix issue",
        "competition": "Draft response",
        "renewal": "Renew plan",
        "reactivation": "Restart campaign",
        "recall": "Book slot",
        "refill": "Confirm refill",
        "compliance": "Show checklist",
        "supply_alert": "Pull batches",
        "profile_verification": "Verify profile",
        "default": "Create offer",
    },
    "opportunity": {
        "performance_spike": "Boost campaign",
        "festival": "Launch offer",
        "event": "Push combo",
        "trend": "Draft post",
        "milestone": "Ask reviews",
        "planning": "Send draft",
        "followup": "Book slot",
        "seasonal": "Update shelf",
        "education": "Send details",
        "default": "Boost campaign",
    },
    "info": {
        "research": "Want summary?",
        "curiosity": "Want numbers?",
        "appointment": "Confirm",
        "default": "Want summary?",
    },
}
